config/routes.rb
AdminSupplysource::Application.routes.draw do
  
  resources :users
  resources :sessions
  resources :products

  # set a root path
  root "static_pages#home"

  # match requests to controller actions
  match '/sign_up', to: 'users#new',  via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'get'

  match '/renderjson/:id', to: 'products#renderJson', via: 'get'

  # ShopperSessions routes
  match '/shopper_sign_up', to: 'shopper_sessions#create', via: 'post'

end

app/models/flag.rb
class Flag < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

	before_save :set_scancounts

	has_attached_file :image

	validates :name, presence: true

	private

		def set_scancounts
			self.track1_scancount ||= 0
			self.track2_scancount ||= 0				
			self.track3_scancount ||= 0
		end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/shopper.rb
class Shopper < ActiveRecord::Base
end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			# return the user if authentication is successful
			user
		else
			# if authentication is not successful, return nil
			nil
		end
	end


	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	helper_method :current_user

private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def signed_in_user
		unless !current_user.nil?
			flash[:danger] = "Please sign in."
			redirect_to login_url
		end
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :signed_in_user, only: [:new, :create, :show, :index, :edit, :update, :destroy]

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)

		if(@product.save)
			flash[:success] = "Successfully added a product"
			redirect_to @product
		else
			render 'new'
		end
		
	end

	# show a specific product
	def show
		@product = Product.find(params[:id])
	end

	# show ALL products in the DB
	def index
		@products = Product.all
	end

	# edit a product
	def edit
		@product = Product.find(params[:id])
	end

	# update a record in the DB
	def update
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to Products_path
	end

	# render a jsonp response
	def renderJson
		@product = Product.find(params[:id])
		render :json => @product.to_json, :callback => params[:callback]
	end

	private

		def product_params
			params.require(:product).permit(:name, :price, :image, :category, :packaged, :calories, :gluten, :protein, :carbs)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:session][:email], params[:session][:password])
  	if user
  		session[:user_id] = user.id
      flash[:success] = "Logged in!"
  		redirect_to root_url
  	else
  		flash.now[:danger] = "Invalid email or password"
  		render 'new'
  	end
  end

  def destroy
  	# clear the user_id session
  	session[:user_id] = nil
    flash[:success] = "Logged out!"
  	redirect_to root_url

  end

end

app/controllers/shopper_sessions_controller.rb
class ShopperSessionsController < ApplicationController

  def create
  		@shopper = Shopper.new(shopper_params)
  		@shopper.save
  end


  private

    def shopper_params
      params.require(:shopper).permit(:email, :password_hash, :track, :first_name, :last_name, :gender, :flag_1, :flag_2, :flag_3, :flag_4, :flag_5)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		# display dashboard if logged in
		
		# render sign-in view if not logged in
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  		@user = User.new(user_params)
  		if @user.save
        flash[:success] = "Signed up!"
  			redirect_to root_url
  		else
  			render "new"
  		end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdminSupplysource</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="topnav">
	<div class="container">

		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-01">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>

		<%= link_to "SUPPLYSOURCE", root_url, class: "navbar-brand" %>

		<!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-collapse-01">
          <ul class="nav navbar-nav navbar-right">
           	
           	<!-- checks to see if the user is logged by seeing if current_user returns true -->
          	<% if current_user %>

	          	<li>
	          		<%= link_to "Products", products_path %>		
	          	</li>

	           	<li>
	           		<%= link_to "#", class: "dropdown-toggle", data:{toggle: "dropdown"}  do%>Metrics <b class="caret"></b><%end%>
	           		<ul>
	           			<li><%= link_to "Wastage", "#" %></li>
	           			<li><%= link_to "Score Breakdown", "#" %></li>
	          			<li><%= link_to "Prices", "#" %></li>
	          		</ul>
	           	</li>
	           	
				<li>
					<%= link_to "Log out", logout_path %>
				</li>

			<!-- navbar to display if user is not logged in -->
			<% else %>

				<li><%= link_to "Sign up", new_user_path %></li>
				<li><%= link_to "Log in", login_path %></li>

			<% end %>

          </ul>
        </div><!-- /.navbar-collapse -->
	</div>
</nav>


<div class="container">

	<% if flash.any? %>
	    <% flash.each do |key, value| %>
			<div class="alert alert-<%= key %> fade in">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= value %>	
			</div>
		<% end %>
	<% end %>

<%= yield %>


</div>


</body>
</html>

app/views/products/_form.html.erb
<div class="col-md-8 col-md-offset-2">

	<%= form_for @product do |f| %>
		
		<fieldset>
			<legend><%=@product.name%></legend>

			<!-- NAME -->
			<div class="form-block">
				<%= f.label :name %>
					<%= f.text_field :name, class: "form-control", placeholder: "Enter product name" %>
			</div>

			<!-- PRICE -->
			<div class="form-block">
				<%= f.label :price %>
					<%= f.text_field :price, class: "form-control", placeholder: "Enter a price" %>
			</div>

			<!-- CATEGORY -->
			<div class="form-block">
				<%= f.label :category %>
					<%= f.text_field :category, class: "form-control", placeholder: "Enter a category" %>
			</div>

			<!-- IMAGE -->
			<div class="form-block">
				<%= f.label :image %>
					<%= f.file_field :image, class: "file-upload" %>
			</div>

			<!-- CALORIES -->
			<div class="form-block">
				<%= f.label :calories %>
					<%= f.text_field :calories, class: "form-control", placeholder: "Enter product calories" %>
			</div>

			<!-- CARBS -->
			<div class="form-block">
				<%= f.label :carbs %>
					<%= f.text_field :carbs, class: "form-control", placeholder: "Enter carbs content" %>
			</div>

			<!-- PROTEIN -->
			<div class="form-block">
				<%= f.label :protein %>
					<%= f.text_field :protein, class: "form-control", placeholder: "Enter protein content" %>
			</div>

			<div class="form-block">

				<!-- PACKAGED? -->
					<div class="checkbox">
						<%= f.label :packaged %>
						<%= f.check_box :packaged %>
					</div>

				<!-- GLUTEN? -->
					<div class="checkbox">
						<%= f.label :gluten %>
						<%= f.check_box :gluten %>
					</div>

			</div>

			<div class="form-block">
					<%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
			</div>
		
		</fieldset>

	<% end %>

</div>

app/views/products/_form_errors.html.erb
<%if @product.errors.any? %>
    <div class="alert alert-danger fade in">
	    	<button type="button" class="close" data-dismiss="alert">&times;</button>
	      	The form contains <%= pluralize(@product.errors.count, "error") %>.
		<ul style="margin-top:5px;">
		<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/products/edit.html.erb
<%= render 'form_errors' %>

<h1>Update Product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>Listing Products</h1>

<%= link_to "Add Product", new_product_path %>

<table class="tablestyle">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Category</th>
    <th>Calories</th>
    <th>Gluten?</th>
    <th>Packaged?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.category %></td>
      <td><%= product.calories %></td>
      <td><%= product.gluten %></td>
      <td><%= product.packaged %></td>
      <td><%= link_to 'Show', product_path(product.id) %></td>
      <td><%= link_to 'Edit', edit_product_path(product.id) %></td>
      <td><%= link_to 'Delete', product_path(product.id),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<%= render 'form_errors' %>

<h1>Create Product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
 
<%= image_tag @product.image.url %>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Track 1 Scan Count:</strong>
  <%= @product.track1_scancount %>
</p>
<p>
  <strong>Track 2 Scan Count:</strong>
  <%= @product.track2_scancount %>
</p>
<p>
  <strong>Track 3 Scan Count:</strong>
  <%= @product.track3_scancount %>
</p>

<%= image_tag("https://chart.googleapis.com/chart?chs=250x250&cht=qr&chl=#{@product.id}&choe=UTF-8") %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>

  <div class="alert alert-danger fade in">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    
    <ul style="margin-top:5px;">
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<!-- if logged in, display the dashboard -->
<% if current_user %>

<!-- Main -->
<div class="container">
  <!-- Upper section -->
    <div class="col-md-12">
    </br>

       <a href="#"><strong><i class="glyphicon glyphicon-dashboard"></i> My Dashboard</strong></a>  
            
       <hr>
       
       <div class="row">
        <div class="col-md-3">
          <div class="tile">
          	<%= link_to image_tag("icons/svg/retina.svg", alt: "Test", class: "tile-image")  %>
            <h3 class="tile-title">Product Scans</h3>
            <br>
            <p><span class="badge">70</span></a></p>
          </div>
        </div>

        <div class="col-md-3">
          <div class="tile">
            <%= link_to image_tag("icons/svg/toilet-paper.svg", alt: "Test", class: "tile-image")  %>
            <h3 class="tile-title">Wastage</h3>
            <br>
            <p><span class="badge">34</span></a></p>
          </div>
        </div>

        <div class="col-md-3">
          <div class="tile">
            <%= link_to image_tag("icons/svg/paper-bag.svg", alt: "Test", class: "tile-image")  %>
            <h3 class="tile-title">Paper Bags Used</h3>
            <br>
            <p><span class="badge">42</span></a></p>
          </div>
        </div>

        <div class="col-md-3">
          <div class="tile">
            <%= link_to image_tag("icons/svg/clipboard.svg", alt: "Test", class: "tile-image")  %>
            <h3 class="tile-title">Inventory</h3>
            <br>
            <p><span class="badge">112</span></a></p>
          </div>
        </div>
      </div> <!-- /tiles -->

      <hr>

	   <div class="row">
            <!-- Center left -->	
         	<div class="col-md-7">
			  		<div class="well">Notifications <span class="badge pull-right">5</span></div>
              <hr>
              
              	<div class="panel panel-default">
                  <div class="panel-heading"><h4>Analytics</h4></div>
                  <div class="panel-body">
                    
                    <small>Hormone-Free Meat:</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100" style="width: 72%">
                        <span class="sr-only">72% Complete</span>
                      </div>
                    </div>
                    <small>Wasted Produce:</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                    <small>Plastic Bags Used:</small>
                    <div class="progress">
                      <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>

                  </div><!--/panel-body-->
              </div><!--/panel-->                     
              
          	</div><!--/col-->
         
            <!-- Center-right -->
        	<div class="col-md-5">
              
				<p>
                  Lorem profile dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate. Lorem profile dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                </p>
                <p>
                  Lorem profile dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate. Lorem profile dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate.
                </p>
              
                <hr>
              
                <div class="btn-group btn-group-justified">
                  <a href="#" class="btn btn-primary col-sm-3">
                    <i class="glyphicon glyphicon-plus"></i><br>
                    Add Supplier
                  </a>
                  <a href="#" class="btn btn-primary col-sm-3">
                    <i class="glyphicon glyphicon-qrcode"></i><br>
                    QR Code
                  </a>
                  <a href="#" class="btn btn-primary col-sm-3">
                    <i class="glyphicon glyphicon-cog"></i><br>
                    Settings
                  </a>
                  <a href="#" class="btn btn-primary col-sm-3">
                    <i class="glyphicon glyphicon-question-sign"></i><br>
                    Help
                  </a>
                </div>
			</div><!-- /col-span-5 -->
        </div><!-- /row -->
  	</div><!-- /col-span-12 -->
  </div><!-- /row -->
  <!-- /upper section -->

  <!-- Lower section -->

  <!-- /lower section -->

</div>  	

<!-- if not logged in, display the static home page-->
<% else %>

	
	<div class="jumbotron">
		
		<h1>Welcome</h1>
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis</p>
		<p><a class="btn btn-primary btn-lg">Learn more</a></p>
		
	</div>
	

<% end %>

app/views/users/new.html.erb
<%= render "shared/error_messages" %>

<h1>Sign Up</h1>

<div class="col-md-8 col-md-offset-2">

	<%= form_for @user do |f| %>

		<!-- form fields -->

		<div class="form-block">
			<%= f.label :email %>
			<%= f.text_field :email, class: "form-control" %>
		</div>

		<div class="form-block">
			<%= f.label :password %>
			<%= f.password_field :password, class: "form-control" %>
		</div>

		<div class="form-block">
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation, class: "form-control" %>
		</div>

		<div class="form-block">
			<%= f.submit "Sign Up", class: "btn btn-lg btn-primary" %>
		</div>
		
	<% end %>

</div>